name: CI

on:
  push:
    branches:
      - '**'        # matches every branch
  pull_request:
    branches:
      - '**'        # matches every branch

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install pytest-cov
        # python -m pip install torch==1.12.1+cpu --extra-index-url https://download.pytorch.org/whl/cpu
        python -m pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
        python -m pip install "jax[cpu]"
        pip install -e .
    - name: Test coverage.
      run: |
        pytest -m 'not big' --cov cola --cov-report xml:cov.xml tests/
    - name: Upload to codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./cov.xml
        name: codecov-umbrella
        verbose: true
